### ISSUE TITLE
Generate random port for new projects?

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#104]
The Rojo CLI should assign a random serve port number to new projects to reduce the probability of collision, potentially?

It's possible that this would just cause extra friction, since the default port is likely enough for most users.

**Comment by Kampfkarren** [comment]
:-1: The type of user to use Rojo is likely the type of user who would understand they'd have to use a different port for more than one project, this just causes annoyance.

**Comment by LPGhatguy** [comment]
I think you're right, and after sleeping on it I think we can skip this!
