### ISSUE TITLE
v0.5.0 alpha server panic when pasting folder into partition when serving

### ISSUE THREAD

**Issue by Avigant** [LPGhatguy/rojo#111]
I get this error in server output:
```
thread '<unnamed>' panicked at 'Tried to link child of path that wasn't a directory!', server\src\imfs.rs:148:21
```

When I exit out of Rojo and restart it, syncing works just fine.

Reproduction steps:
1. Make a Rojo folder.
2. Make an X folder in the Rojo folder.
2. Initialize Rojo in the Rojo folder.
3. Point a Rojo partition to X.
4. Start the server.
5. Paste a non-empty folder into X or a descendant of X.

**Comment by LPGhatguy** [comment]
I'll see if I can reproduce this with the latest Git master or not!

**Comment by LPGhatguy** [comment]
I've reproduced this!

I didn't hit this because I didn't expect to receive a file created event before the operating system told me that the directory was created.
