### ISSUE TITLE
Rojo crashes if child directory does not have "$classname"

### ISSUE THREAD

**Issue by Nimblz** [LPGhatguy/rojo#128]
Rojo panics with `thread 'main' panicked at 'Could not snapshot project tree: ProjectNodeUnusable', src\libcore\result.rs:1009:5` if a child directory does not have its classname defined

Example project:
```
{
  "name": "not eg",
  "tree": {
    "$className": "DataModel",
    "ReplicatedStorage": {
      "$className": "ReplicatedStorage",
      "common": {
        "$path": "src/common"
      },
      "lib": {
        "Roact": {
          "$path": "module/roact/lib"
        },
        "Rodux": {
          "$path": "module/rodux/lib"
        },
        "RoactRodux": {
          "$path": "module/roact-rodux/lib"
        },
        "t": {
          "$path": "module/t/lib/t.lua"
        }
      }
    }
  }
}
```
# Expected
Rojo to create `"lib"` as a folder in `ReplicatedStorage`, and for the various submodules to exist under it, or for Rojo to explain that `"$classname"` is ambiguous and must be declared

# What happens
Rojo panics with `thread 'main' panicked at 'Could not snapshot project tree: ProjectNodeUnusable', src\libcore\result.rs:1009:5`

This panic can be avoided by specifying that `"lib"` is a folder with `"$classname": "Folder"`
```
...
"lib": {
  "$classname": "Folder",
  ...
}
```

**Comment by LPGhatguy** [comment]
This should be fixed in latest master!
