### ISSUE TITLE
Syncing into non-default services creates folders instead

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#13]
Right now, if a sync targets a service that isn't instantiated by default like `Teams` or `TestService`, that service will just be created as a folder.

The reconciler should attempt to instantiate services inside of the data model before trying to create folders.

The easy workaround for now is to insert the services before trying to sync with Rojo. I think that's reasonable.

**Comment by LPGhatguy** [comment]
Fixed in latest master.

**Comment by LPGhatguy** [comment]
Not fixed in latest master, agh!

**Comment by LPGhatguy** [comment]
Fixed for v0.4.0-pre2!

**Comment by Nezuo** [comment]
This doesn't seemed to be fixed for me. I am on ``v6.0.0-rc.1``.

Project File:
```json
{
  "name": "Test",
  "tree": {
    "$className": "DataModel",

    "TestService": {
      "$path": "src"
    }
  }
}
````

Result:
![image](https://user-images.githubusercontent.com/48431591/98901538-cc6fa680-2468-11eb-992b-43c168ee8c00.png)

**Comment by LPGhatguy** [comment]
Thanks for looking for an existing bug, but this one is from a very different era of Rojo. 😅

Your issue is the same as #331. I'll update that issue's title to explain the underlying issue and whether we should consider it a bug or just something to document.
