### ISSUE TITLE
"rojo init" creates an invalid default.project.json

### ISSUE THREAD

**Issue by EthanCurtiss** [LPGhatguy/rojo#136]
I took this straight from the [documentation](https://lpghatguy.github.io/rojo/0.5.x/creating-a-place/):

![image](https://user-images.githubusercontent.com/41402526/54651773-b5f22b80-4a8a-11e9-876e-787c6c68d98d.png)

**Comment by LPGhatguy** [comment]
This is fixed in current master (https://github.com/LPGhatguy/rojo/blob/master/CHANGELOG.md), I'll push out a new release this week that should smooth out this issue.
