### ISSUE TITLE
Rojo crashes when trying to sync a LocalizationTable with an integer field

### ISSUE THREAD

**Issue by OrbitalOwen** [LPGhatguy/rojo#145]
If an entry in a LocalizationTable is solely an integer Rojo crashes with the following error:

```
[ERROR rojo] Details: Malformed localization table found!: Error(Deserialize { pos: Some(Position { byte: 3771, line: 26, record: 26 }), err: DeserializeError { field: None, kind: Message("invalid type: integer `350`, expected a string") } })
```

**Comment by LPGhatguy** [comment]
Weird! I wonder if this is a bug with the underlying CSV library.

**Comment by LPGhatguy** [comment]
I was able to reproduce this and I'm still trying to figure out if this is a bug in csv or a bug in Rojo. I started out thinking it was _definitely_ a csv bug, but now I'm not so sure.
