### ISSUE TITLE
Studio fails to load from rbxlx if Content is null

### ISSUE THREAD

**Issue by dordin** [LPGhatguy/rojo#146]
Roblox Studio fails to load rbxlx files built with v0.5.0 Alpha 8:

```
TextXmlParser::parse - Unknown tag 'null /'.
```

To reproduce, save a Decal with no texture and try to build a project with it.

The Content generated with Studio:
`<Content name="Texture"><null></null></Content>`
and with Rojo:
`<Content name="Texture"><null /></Content>`

**Comment by LPGhatguy** [comment]
Ah, this should be a pretty straightforward fix.

The XML library that rbx_xml uses has a flag called `normalize_empty_elements` on by default in `EmmitterConfig`: <https://docs.rs/xml-rs/0.8.0/xml/struct.EmitterConfig.html>. That seems like a pretty bad default, I wonder why it's set by default.

**Comment by dordin** [comment]
Another bad default is `indent_string`, which is two spaces instead of a tab.

**Comment by LPGhatguy** [comment]
This was fixed in https://github.com/LPGhatguy/rbx-dom/commit/b130072a15674f5106701f07e678f0136cc4f5df and should be applied when Rojo updates to the next `rbx_xml`!
