### ISSUE TITLE
`Serialize` is defined multiple times, build failing

### ISSUE THREAD

**Issue by OrbitalOwen** [LPGhatguy/rojo#175]
```
error[E0252]: the name `Serialize` is defined multiple times
  --> C:\Users\Owen\.cargo\registry\src\github.com-1ecc6299db9ec823\rojo-0.5.0-alpha.9\src\project.rs:13:13
   |
12 | use serde_derive::{Serialize, Deserialize};
   |                    --------- previous import of the macro `Serialize` here
13 | use serde::{Serialize, Serializer};
   |             ^^^^^^^^^ `Serialize` reimported here
   |
   = note: `Serialize` must be defined only once in the macro namespace of this module
help: you can use `as` to change the binding name of the import
   |
13 | use serde::{Serialize as OtherSerialize, Serializer};
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0252`.
error: failed to compile `rojo v0.5.0-alpha.9`, intermediate artifacts can be found at `C:\Users\Owen\AppData\Local\Temp\cargo-installppxfhu`

Caused by:
  Could not compile `rojo`.
```

Related?
https://github.com/serde-rs/serde/issues/1441

**Comment by Kampfkarren** [comment]
I've dealt with this before in my own work, going to make a PR to fix this.

**Comment by Kampfkarren** [comment]
Actually, I'm not sure how you're getting this. Can you send your `rustc --version`?

**Comment by OrbitalOwen** [comment]
`rustc 1.35.0 (3c235d560 2019-05-20)`

**Comment by Kampfkarren** [comment]
The rojo build may just not be up to date yet. This was fixed in https://github.com/LPGhatguy/rojo/commit/27e2612fc9368554429cbaa766169edfa6d1f702

**Comment by LPGhatguy** [comment]
Oof, this is a hell of a footgun I hit here!

One of the dependencies I control (one of the rbx-dom crates) started depending on Serde with the `derive` feature set instead of serde + serde_derive, just like the linked issue mentions. The easy fix is to make sure everything up/down the stack stops depending on serde_derive and instead only depends on serde!

**Comment by LPGhatguy** [comment]
Should be fixed in alpha 11.
