### ISSUE TITLE
The ConnectionActivePanel obscures too much of viewport

### ISSUE THREAD

**Issue by ZachCurtis** [LPGhatguy/rojo#177]
my guis are generated at runtime from lua but this makes previewing designs a time sink so I use a plugin to preview them in studio. At the time of this writing I have a white notification label of sorts that I think I want it to go where Rojo wanted to go, but I can't see it, and I can't z index my way above rojo this time. 

Filing a github issue takes a bit less time than it does to navigate all the way to the end of the toolbar to where Rojo's Connect button was before last hour's studio update, then back to the other end where it will be until the next update. Having to do this every single time I want to sync and preview a change is killing my workflow.

I could just start remembering the side of the toolbar that Rojo is on earlier than just before the next update, but I think Rojo could instead offer a sort of minimize button. This would hide the ConnectionActivePanel label until the next change is synced in, and possibly have a confirmation step, warning about leaving the plugin polling without a heads up indication.

**Comment by LPGhatguy** [comment]
It seems like it would be a good idea to port Rojo's UI over to a dock widget, then it can be out of the way for everyone!

**Comment by LPGhatguy** [comment]
Fixed in latest master, the new UI is tucked away in a plugin GUI that can be hidden:

![unknown (1)](https://user-images.githubusercontent.com/654598/59316161-de488b00-8c71-11e9-846c-3318629c5149.png)
