### ISSUE TITLE
Implement 'rojo build'

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#18]
One of Rojo's goals is to replace [rbxpacker](https://github.com/LPGhatguy/rbxpacker).

This is in the form of a command called `rojo pack`, which needs to be fleshed out to work with things like multiple partitions.

**Comment by LPGhatguy** [comment]
The scope of this might expand to be much more than rbxpacker!

It'd be nice to output quasi-binaries in `rbxmx` and `rbxlx` format for use in automated testing. The workflow for `rbxmx` files would probably be better than generating Lua install scripts!

**Comment by Kampfkarren** [comment]
Don't the Roblox packages announced at RDC solve this issue?

**Comment by LPGhatguy** [comment]
I don't think there are any command line tools announced officially from Roblox at all. The goal of this tool would be to get a Continuous Delivery (CD) pipeline up and running instead of having to manually build release artifacts from Studio.

**Comment by LPGhatguy** [comment]
The XML format works in `master`, and the binary format is pretty close behind, thanks to [rbx-tree](https://github.com/LPGhatguy/rbx-tree).

**Comment by LPGhatguy** [comment]
This is done for binary and XML formats for both models and places.
