### ISSUE TITLE
Tools don't sync properties properly

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rojo#186]
Creating a `.model.json` (or soon `.meta.json`) of a Tool will not sync their tool specific properties properly.

The following is a valid tool

```
{
	"Name": "Tool",
	"ClassName": "Tool",
	"Properties": {
		"GripForward": [-1, 0, 0],
		"GripPos": [0, 0, -1.3],
		"GripRight": [0, 1, 0],
		"GripUp": [0, 0, 1]
	}
}
```

...will sync as

![RobloxStudioBeta_y9fMixmHor](https://user-images.githubusercontent.com/3190756/58886923-84582c00-8699-11e9-8974-65455871fb4a.png)

The reason for this is not Rojo, but instead what naturally happens when you try to edit these properties--they'll collide(?) with each other and change each other.

The solution as I see it is to especially check for Tools setting these grip properties and instead combining them to a CFrame and using [Grip](https://developer.roblox.com/api-reference/property/Tool/Grip).

**Comment by Kampfkarren** [comment]
Using `Grip` in the command line with this value:

![image](https://user-images.githubusercontent.com/3190756/58887474-8969ab00-869a-11e9-9cd5-dbe9161a9123.png)

**Comment by Kampfkarren** [comment]
Creating a Tool by hand and putting this in the command line:

```
workspace.Tool.Grip = CFrame.fromMatrix(
	Vector3.new(0, 0, -1.3),
	Vector3.new(0, 1, 0),
	Vector3.new(0, 0, 1),
	-Vector3.new(-1, 0, 0)
)
```

...returns the *correct* grip. Tools also document what part of the CFrame their grip properties are using (R00, etc), so this could be used from the `rbx_snapshot` side.

**Comment by LPGhatguy** [comment]
Special-casing snapshots just for tools feels like the wrong approach here. We don't want to muck with properties from files and this is a sync-specific quirk.

We could:
- Tell people to just define Grip instead
- Fix this in rbx_xml and rbx_dom_lua

**Comment by Kampfkarren** [comment]
Latter is a lot more user friendly, I'm in favor of that. Not sure where rbx_xml comes into play, though.

**Comment by LPGhatguy** [comment]
After talking about this internally and also on some people with Discord, I think the solution is to push people to use the `Grip` property directly.

The `GripForward`/`GripUp`/`GripRight`/`GripPos` properties were introduced as a workaround for the lack of a CFrame editor in Studio it sounds like. Since it isn't hard to just list out a CFrame in your project file (it'll have the same values listed, just as columns in a matrix), I don't think we need to do anything on Rojo's side.
