### ISSUE TITLE
Sound Error

### ISSUE THREAD

**Issue by TheQuinnn** [LPGhatguy/rojo#187]
I'm getting the following error inside of the Roblox Studio console when I have a "Sound" instance bundled in a .rbxmx file.

` [Rojo-Warn] Plugin_1997686364.Rojo.Plugin.Reconciler:154: Invalid property xmlRead_MaxDistance_3 on class Sound: xmlRead_MaxDistance_3 is not a valid member of Sound`

Let me know if you need any more information. 👍

**Comment by LPGhatguy** [comment]
Good find! I'll get that information where it needs to go and fix this for the next release!

**Comment by LPGhatguy** [comment]
Should be fixed in `master`, I'll push out 0.5.0-alpha.12 tonight that should have this fixed, too.
