### ISSUE TITLE
rojo.exe Refusing to Open

### ISSUE THREAD

**Issue by chexburger** [LPGhatguy/rojo#188]
Whenever I run the rojo.exe file that I've downloaded, it opens for a split moment only to show in the taskbar then closes again. Same goes for opening rojo.exe in the cargo bin folder. I've restarted my PC numerous times.

I'm unsure if there's even supposed to be an interface either. If there isn't, this isn't a problem then.

**Comment by Kampfkarren** [comment]
There is no GUI interface, it's only CLI.

**Comment by LPGhatguy** [comment]
I recently updated the documentation to try to make this a little more clear. 😄 

If there's a specific spot you think we can add a notice about how Rojo is a command-line tool, let me know!
