### ISSUE TITLE
High CPU usage in a small project

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#21]
Holy cow this is some high CPU usage:

![image](https://user-images.githubusercontent.com/654598/34055341-93287ad0-e183-11e7-9492-4339d7f1fa00.png)

Rojo needs to _not_ do that. My hunch is that the file watcher either has a bug or is falling back to polling because of some missing API support.

**Comment by Quenty** [comment]
Definitely caused by infinite loops without sleeping. I've submitted a pull request to fix it.
