### ISSUE TITLE
Support using game as a partition target

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#26]
Other syncing systems, like studio-bridge or RbxRefresh, sync from the top of the Roblox hierarchy.

As part of fixing service support when syncing into game, Rojo should also support this use case. Notably, this means _not_ wiping away unknown objects when the current item is game.

**Comment by Kampfkarren** [comment]
With RbxSync becoming archived (and also suddenly breaking without me updating), this is required for my project, alongside making sure non-script objects inside scripts don't get deleted by rojo.

**Comment by LPGhatguy** [comment]
Done in epiphany on Git master.
