### ISSUE TITLE
Protocol v1 Design Issue

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#27]
There's an issue with the new protocol (v1) that I'm trying to resolve but having trouble with.

Given the following filesystem tree:

```
src
|-- foo.lua
```

Rojo should produce the following Roblox hierarchy:

```
src (Folder)
|-- foo (ModuleScript)
```

If `foo.lua` is renamed to `foo.not-lua`, the file watcher will tell the plugin that these paths changed:

```json
[["src", "foo.lua"], ["src", "foo.not-lua"]]
```

The plugin issues a read for these paths, and gets back this result from the server:

```json
[null, ["details about foo.not-lua"]]
```

The plugin tries to reconcile the `["src", "foo.lua"]` to be nil, but won't be able to find anything to delete, since the object is named `foo`, not `foo.lua` -- we'd have to map the file name to a `Name-ClassName` pair!

The plugin ends up creating this tree:

```
src (Folder)
|-- foo (ModuleScript)
`-- foo.not-lua (StringValue)
```

This differs from the tree we would get if we did a fresh sync, which is not good!

**The protocol needs to be modified to communicate paths in a different way, but I'm not entirely sure how to progress.**

## Soution 1: Use `Name-ClassName` pairs for all route entries
Instead of getting a change as `["src", "foo.lua"]`, we'd get a change as `[["src", "Folder"], ["foo", "ModuleScript"]]` -- this requires plugins to do a little bit more work when transforming files, but not too much more.

This runs into a problem when it comes to the current `JsonModelPlugin` implementation -- we don't know the `ClassName` of an object until we read the file. If a file is deleted, we have no way to recover the identity of the object with this idea! Normally, we'd be able to change the plugin's convention to include the `ClassName` in the file name, but that won't be possible when `rbxlx` and `rbxmx` support is added, which have arbitrary parent containers.

## Solution 2: Keep an index that maps routes to instances
This solution would introduce a map from VFS routes to Roblox instances in the  plugin while it's syncing.

When the plugin picks up a change from the server, it figures out what object is affected, and can use this to destroy that object if a `null` result is received. Any time an object is modified, the index would be updated.

Since partial sync operations only happen when a portion of the tree is read, the map doesn't need to stick around for very long.
  
The major issue I see occurs when the user mutates objects that are in the index (which will happen with bi-directional syncing) it might be difficult to update or discard the correct portions of the index.

## Solution 3: Keep the entire tree in-memory on the server
This acts like an extension to solution 2, but implemented on the server. Instead of reading from the disk on demand, Rojo can limit reads to when files change, keeping the results in memory. The total number of reads should be the same, so performance should be fine.

This solution has the same advantages as solution 2, but with the advantage that the user can't mutate objects in the index directly, simplifying a lot of operations.

**Comment by LPGhatguy** [comment]
I implemented solution 2 as a hack here:
https://github.com/LPGhatguy/rojo/tree/route-index-experiment
https://github.com/LPGhatguy/rojo-plugin/tree/route-index-experiment

The code here isn't great, but it does demonstrate that the idea works for current cases.

**Comment by LPGhatguy** [comment]
I'm going to implement solution 3 on another branch following the refactoring I've done today.

**Comment by LPGhatguy** [comment]
I think solution 3 is actually really difficult to implement correctly.

I've added `route` as a property of `RbxInstance` objects and will be moving forward with solution 2, with the intent to cross the bidirectional syncing bridge when I need to.

**Comment by Quenty** [comment]
I think solution 3 is really messy and that solution 1 feels especially messy given that isn't the data trying to be sent. 

I think solution 2 models the situation the best. Solution 3 is especially messy because it makes the server extremely stateful in respect to the plugin, whereas solution 2 can desync and resync without major issues.

**Comment by LPGhatguy** [comment]
I sort of came to the same conclusion thinking about this over the weekend.

Everything is in place in the server to support solution 2, I'm just working on implementing that cleanly in the plugin. Once that's in place, I'll hammer on it for awhile and then the new protocol should be ready for stabilization!

**Comment by LPGhatguy** [comment]
Solution 2 is implemented and in the prerelease to see if there are any further problems.

**Comment by Quenty** [comment]
Nice.
