### ISSUE TITLE
Plugin: Syncing with path pointing to service errors

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#29]
Plugin issue:

![image](https://user-images.githubusercontent.com/1774409/34847006-8ff182f0-f6df-11e7-8364-303ed2de7013.png)

**Comment by LPGhatguy** [comment]
Yep, that's definitely supposed to work, and does in 0.3.x!

**Comment by LPGhatguy** [comment]
Fixed in latest master, will have a pre-release soon.
