### ISSUE TITLE
Should not have to specify type of property for basic value types in json

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#31]
I know serde json parses using this type system, but it'd be really nice if properties didn't have to be specified as boolean, number, string, et cetera.

**Comment by LPGhatguy** [comment]
I'm torn on this one.

On the one hand, having an explicit format with few optional points like this makes it easier to parse and handle by other tools. The JSON format is designed first as a transmission format and less as a storage format.

On the other hand, from an ergonomics perspective the types definitely should be optional!

**Comment by LPGhatguy** [comment]
I'm revisiting this problem as part of trying to improve the configuration ergonomics and breaking out Rojo's storage format into a separate project.

It'd be nice if strings, numbers, and boolean values can serialize as their literals, while everything else would turn into a map with a `type` field as a discriminant.

**Comment by Quenty** [comment]
I agree entirely with this. JSON definitely has types for:

- Strings
- Numbers/Integers
- Booleans

And does not have literals for any other primitive data type. For this reason, it makes sense to me that being verbose with those types is ok. 

There are certainly arguments for not being implicit for Color3, et cetera. i.e

```json
"color": [135, 35, 135] 
```

as a smaller storage than 
```json
"color": {
    "type": "Color3",
    "r": 135,
    "g": 35,
    "b": 135
}
```

Whereas the first is easier to read and write for advance users, but will be harder to debug, reason about, and requires assumptions made by the parser.

However, I assume the following things

* Most property changes will be done by 2-way sync, not manual editing
* Primarily reading JSON will be done by git
     * Need to avoid reordering for this reason
     * More verbose version clarifies what is changing, but at the same time adds a lot more code to read/scan through

Overall both will be fine, but I think the second is more clear to debug. It'll be a lot easier to write the first by hand.

**Comment by LPGhatguy** [comment]
Yeah, two-way syncing will make the majority of hand-editing obsolete.

Types do need to be encoded into the value, so `"color": [135, 35, 135]` is probably out, but `"colorValue": { "color": [135, 35, 135] }` is probably fine.

I'm working on a library and standard format for representing Roblox types in Rust and Lua, as well as implementations of a JSON format (described by this issue!) and the rbxmx format. Right now, a Color3 value will be encoded as:

```json
"BackgroundColor3": {
    "type": "Color3",
    "value": [0.7234, 0.2545, 0.7234]
}
```

**Comment by LPGhatguy** [comment]
The library I mentioned is available: https://github.com/LPGhatguy/rbx-tree

It doesn't include any custom (de)serialization code yet, so everything looks just like it did with Rojo 0.4.x, but it did open up a nice spot to stick any of that logic.
