### ISSUE TITLE
Disabled script suffix

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rojo#34]
Can we have an option to automatically add a suffix to disabled scripts?

Like, if I have a server script called Foobar that's disabled, I want it to write as Foobar.DISABLED.server.lua

**Comment by LPGhatguy** [comment]
That's a good idea, but I don't know if a suffix is the best way to do it.

**Comment by Kampfkarren** [comment]
I use a suffix more my homebrew .rbxlx to folder program just because it makes it easier to read when I put it in a repository.

**Comment by LPGhatguy** [comment]
Closing in favor of #123, which gives Rojo a path to represent disabled scripts.
