### ISSUE TITLE
Plugin should allow user to choose port to listen on

### ISSUE THREAD

**Issue by Avigant** [LPGhatguy/rojo#45]
Sometimes I like to work on two projects at the same time. While I can change the port number to serve on in rojo.json, I don't believe there's an option to configure the port the plugin should look for.

If this were to be implemented, it would also be good to give a better error message when two Rojo instances serve on the same port, and you attempt to sync. The current one when I have a partition for game.ServerScriptService is:

19:19:24.734 - The Parent property of ServerScriptService is locked
19:19:24.734 - Stack Begin
19:19:24.735 - Script 'Plugin_1211549683.Rojo.Reconciler', Line 169 - field reconcile
19:19:24.735 - Script 'Plugin_1211549683.Rojo.Reconciler', Line 266 - field reconcileRoute
19:19:24.736 - Script 'Plugin_1211549683.Rojo.Plugin', Line 120 - method _pull
19:19:24.736 - Script 'Plugin_1211549683.Rojo.Plugin', Line 172
19:19:24.737 - Stack End

**Comment by LPGhatguy** [comment]
Thanks for filing the issue and bringing it up still!
