### ISSUE TITLE
Duplicated scripts synced into tree

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#48]
I noticed this working on hack week with another engineer, where we reopened our place file and started/stopped polling a lot. We'd end up with one or two different scripts duplicated multiple times. This manifested as Rojo looking like it was broken, since the changes we were making didn't look like they were applying.

If you hit this bug, it's safe to revert to 0.3.x until I get around to fixing 0.4.0 with a patch release.

**Comment by LPGhatguy** [comment]
I believe this may have been addressed in the latest master, but I'm unsure.

**Comment by Quenty** [comment]
Is this published to cargo yet? Will `cargo install rojo --force` update?

**Comment by LPGhatguy** [comment]
Yep, 0.4.1 has been published in the releases section and on Cargo.

Let me know if this fixes your issue -- I had trouble reproducing this after hack week.
