### ISSUE TITLE
Add version number to project file?

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#52]
Before making any breaking changes, it seems like it would be a good idea to add a (required?) version parameter to the file to introduce new mechanics without breaking existing files.

**Comment by ryan-c-scott** [comment]
I just started looking at making Rojo pull the git project rev + branch and sending that information back to Studio as a lua file.  The use case is working on a team and needing to know which version of the code is running on various places.

**Comment by LPGhatguy** [comment]
Embedding build metadata might be useful as a separate feature or process. One roadblock I've run into in the past trying to embed revision/branch metadata in the regular dev process is that uncommitted changes can be in your working directory. That issue generally makes commit hashes unreliable unless you also generate the builds from a CI machine.

This issue is for a different feature, which is versioning the project format itself, so that if we wanted to make breaking changes to the format or reuse old keys, it'd be easier to disambiguate the user's intent.
