### ISSUE TITLE
Invalid Windows Filenames

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/rojo#53]
Forgive me if this has already been accounted for, I'm not at home to test...

In my game, Battle Hats, I have a folder for every hat in the game. The hat that destroys every solution under the sun that's not my awful homebrew one is "Noob Attack: Periastron", because you can't use colons in Windows. In my homebrew solution, I replace the colon with a smaller unicode colon. Is there anything like this, even just by removing the colon, in rojo?

**Comment by LPGhatguy** [comment]
Wow, I don't think that's a very good solution to this problem.

You should name your instances something else, and use actual value objects or such for your user-facing names.

**Comment by Kampfkarren** [comment]
It is an awful solution, Eryn's RbxSync just straight removes the characters (which is a fine solution). If I were to use something else at this point, I'd need to refactor a lot of my code.

**Comment by LPGhatguy** [comment]
Is there a reason why you can't make that unicode substitution in your game instead? Rojo would be able to handle that gracefully, as long as you don't use objects that you can't use on the filesystem.

If anything, Rojo will probably just throw a better error when you try to make files like that, instead of trying to replace or fix them.

**Comment by Kampfkarren** [comment]
Because the way I store the player's inventory is through names because they should stay constant (a method with arguable reprocussions). Substituting the name in my game requires me to write snowflake code when checking inventories to make sure it gets replaced, and I really don't want to do that. The unicode character is also kind of ugly on GUIs. 

An error in rojo is fine, a developer might be confused on why some of their files or folders aren't being ported. Personally, I'm probably just going to clone rojo just for this functionality.

**Comment by LPGhatguy** [comment]
After talking with some people internally, using `Instance.Name` for display names is something we really don't want people doing. It interferes with localization and causes issues like this with filesystem representation.

The current exceptions are:
* Tools
* Humanoids
* `SortOrder.Name`

**Comment by Kampfkarren** [comment]
All of which I'm using in relation to these names.

**Comment by Kampfkarren** [comment]
Also, in relation, to wontfix, it's still an issue that developers might be completely unaware their scripts aren't transferring over (whether using Instance names is good or not). I think a good middleground would be flashing a warning if it contains invalid Windows naming, and not try to save it.

**Comment by LPGhatguy** [comment]
We can't know if a filename would be invalid on Windows until we try to save it. Different platforms have different restrictions in that regard.

Since Rojo only does syncing into studio right now and not out, it isn't an issue that we should hit right now.
