### ISSUE TITLE
Allow syncing individual files

### ISSUE THREAD

**Issue by AmaranthineCodices** [LPGhatguy/rojo#57]
I develop using a single-script methodology. Right now, Rojo makes me have a weird folder structure to synchronize my entry points into Studio correctly:

```
src
- serverMain
  - init.server.lua
```

It'd be nice to specify a file as a partition target:

```js
"serverMain": {
    "path": "src/ServerMain.server.lua",
    "target": "ServerScriptService.Server"
}
```

**Comment by LPGhatguy** [comment]
Usually the way I work around this is by putting my entrypoints on the client/server into folder, but it's... not ideal.

**Comment by LPGhatguy** [comment]
I'm bumping this up to 0.4.5, I feel like this should've worked from the start.

**Comment by LPGhatguy** [comment]
This should be fixed in the latest master.

It was a pretty straightforward fix, but it might have other repercussions. If you could give it a try and let me know if it works, that'd be awesome!
