### ISSUE TITLE
Rojo should error when no project file is found

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#63]
The default behavior of

```bash
$ rojo serve
Found no project file, using default project...
Server listening on port 8000
```

is a bad pattern since the "Server listening on port 8000" implies all is well. Instead, rojo should warn with red and quit immediately to signal something is wrong.

I've found myself more than once thinking things are fine and syncing when they really aren't.

**Comment by LPGhatguy** [comment]
Agreed.

The current 'impl-v2' branch fixes this, but I think I should break this for 0.4.5 as well, since the default project behavior is completely useless!

**Comment by Quenty** [comment]
Thank you!
