### ISSUE TITLE
Support init.json to initialize a specific instance type

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#66]
Support init.json to initialize a specific instance type

**Comment by LPGhatguy** [comment]
A much earlier version of Rojo actually supported this, but ran into issues with the implementation because it would pick up `init.spec.lua` and similar files as well!

This would make building Tools much easier with Rojo, which would address some other peoples' minor Rojo issues

**Comment by LPGhatguy** [comment]
It's in master!
