### ISSUE TITLE
Polling label doesn't disappear sometimes

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#67]
It appears there may be an uncaught error in the polling system that leaves the label around. @ZoteTheMighty should have more details.

**Comment by ZoteTheMighty** [comment]
Looks like it's an issue that occurs during plugin development.  Repro:

1. Turn on polling.
2. Save a local plugin, which causes plugins to refresh

You'll still see the polling label on the screen, but polling will have stopped when the plugin stopped.

Solution would be to check for and clean up the label on startup.  *Technically* you could try to leave something in the workspace that indicates that polling should start back up after plugin refresh, but that starts to get messy.

**Comment by LPGhatguy** [comment]
I took this approach a step further.

Like suggested, when Rojo starts up, I check for an existing label and clean it up if it's present.

What I _also_ do is listen for the plugin's label to be destroyed, and if it is, I assume it's Roblox Studio signalling that the plugin is being replaced by a new instance (since the new instance would destroy the previous one's UI). That gives us a signal that we can use to stop any polling, get rid of any signals, etc.
