### ISSUE TITLE
Rojo syncs all json specified instances as StringValues with the json as StringValue.Value.

### ISSUE THREAD

**Issue by Avigant** [LPGhatguy/rojo#71]
I am using the verbatim JSON from the documentation: https://lpghatguy.github.io/rojo/sync-details/

When I sync, it inserts a `StringValue` at the correct location, but `StringValue.Name` is the file name (i.e. test.json) and `StringValue.Value` becomes the JSON.

I also tried this and it seems to occur with all JSON. I have received no error with this, and everything else continues to sync normally.

**Comment by Avigant** [comment]
Problem was you need to name your files `*.model.json`, this wasn't specified in documentation at time I filed.

**Comment by LPGhatguy** [comment]
Let's keep this open until I fix that gaping docs hole 😄
