### ISSUE TITLE
Rojo locks created folders in directories Rojo is watching on windows when running

### ISSUE THREAD

**Issue by Quenty** [LPGhatguy/rojo#82]
Rojo locks created folders on windows when running. This makes it impossible to delete folders on directories crated in a directory that rojo is watching

1. Run rojo on a directory
2. Create a folder
3. Try to delete it

Expected result: Folder is deleted
Actual result: Folder is used by another program. 

Stopping rojo fixes this. 

Windows Version: 1803 - 17134.165
Rojo version: 0.4.11

**Comment by LPGhatguy** [comment]
I can't reproduce this. I normally have this problem with programs like Sublime Text 3, however.

Rojo doesn't do anything to lock folders, and only reads files from the disk when the plugin requests them.

**Comment by Quenty** [comment]
Yep. This seems to be the case! Sorry about this!
