### ISSUE TITLE
Epiphany Refactor

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#86]
I have a high degree of confidence that this is a great design for Rojo, now there's just a big of implementation work. Everything is happening against `master`.

## Protocol Features
* [x] Port negotation
	* Use a fixed port for now?
	* Via fixed port service?
	* Via server settings tricks?
        * Current solution is via prompting the user for a port number

## Server
* Unit tests
    * [x] Project loading
* Integration tests
    * [ ] Test projects
* [x] Map FS objects into instances
* [x] Map FS events into instance changes
* [x] Map instance changes into messages
* [x] Implement `ignore_unknown` field on project
    * [x] Infer value for known class names? Maybe just default to `true` for everything except `SyncPoint`.
* [x] Implement `ignore_unknown` on instances for client consumption
* [x] Smarter reconciler (name matching heuristics)
* [ ] Project nesting
* [ ] Batched change events
* [ ] Support `.model.json` files or have migration path
* [x] `$properties` field in project format
* [x] `rojo init` command implementation
* Stretch Features
    * [ ] Support syncing rbxmx into tree
    * [ ] Support syncing rbxm into tree

## Client
* [x] Strip out legacy API stuff
* [x] Verify error handling
* [x] Implement constructor
* [x] Implement reconciler
* [x] Cleanup
* [x] Finish deletion routine
* [x] Implement instance addition
* ~Tracking for two-way sync~
* ~Value types other than primitives~
* [x] Config UI
* [ ] Icons
* [x] Error recovery
* Bugs
    * [x] Editing an `init.lua` file screws up the hierarchy

## General
* [x] Update docs
* ~Automatic plugin installation?~

**Comment by Kampfkarren** [comment]
Testing should definitely be in lemur if for no other reason than it's the perfect opportunity to add more missing functionality.

**Comment by Kampfkarren** [comment]
Looking at the JSON, I have some concerns specifically with class names. 

1. It seems redundant to have ReplicatedStorage className: ReplicatedStorage. I understand it's to be generic, but maybe there's a better solution?

2. Might want to default to className: Folder if not already, writing className: Folder everywhere also seems like a pain. 

3. It seems the path sync points ($path) don't specify a className, what's the deal with that? Is that the old Rojo behaviour?

**Comment by LPGhatguy** [comment]
`$className` will be inferred when possible if it isn't specified in a slightly-future version. It's not to be generic, it's to be correct in all cases.

Default class name has me torn. On the one hand, it should be a lint (hey you forgot `$className`) but I suspect you'll be right about folders. Best solution is probably to make a tool to build the config.

Sync points don't specify `$className`, right, because the thing we're pulling in determines what the resulting `ClassName` will be.

**Comment by Kampfkarren** [comment]
#5 also probably helps with my second bullet point.

**Comment by LPGhatguy** [comment]
All of these items have either been done or have been tranferred to other issues. The refactor is pretty much complete!
