### ISSUE TITLE
Epiphany .model.json strategy?

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#97]
0.4.x supports `.model.json` files for representing simple instances on-disk. The current `master` branch doesn't support these yet, and I'm not entirely sure if it should, and if so, in what form.

**Comment by Kampfkarren** [comment]
I believe yes: .model.json files sound like they make it easy to use prefabs by sharing symbolic links around, although I'm not sure if there could be a better solution in mind for that.

**Comment by LPGhatguy** [comment]
Implemented! It was pretty trivial, we can keep this around.
